### PR TITLE
Eliminate last vestiges of travis

### LINKED ISSUE #153: Move from Travis and Bintray to Github Actions
Bintray will shut down on May 1, so there is a need to move hosting for binaries. The preliminary idea is to move to attaching binaries as assets to releases, as is already being done for [Ipopt](https://github.com/coin-or/Ipopt). This seems like an opportune time to also consider moving from Travis to Github Actions, which provides more functionality.

### PR DESCRIPTION
**Pull request by xmunoz**
Third pass at #153.

### CODE REVIEW

**Comment by xmunoz** [comment]
For this PR, I would recommend the "Square and Merge" option after you approve.

**Review by tkralphs — APPROVED** [review]
Looks good!

**Comment by tkralphs** [comment]
I guess you meant "Squash and Merge" :)? Yes, good idea, that's what I did on #156, too.

**Comment by xmunoz** [comment]
:P yes

**Pull request merged**
