### PR TITLE
Add release automation for tag pushes

### LINKED ISSUE #153: Move from Travis and Bintray to Github Actions
Bintray will shut down on May 1, so there is a need to move hosting for binaries. The preliminary idea is to move to attaching binaries as assets to releases, as is already being done for [Ipopt](https://github.com/coin-or/Ipopt). This seems like an opportune time to also consider moving from Travis to Github Actions, which provides more functionality.

### PR DESCRIPTION
**Pull request by xmunoz**
- Always build static and shared for every linux distro
- Remove old AUTHORS file
- Upload artifacts for CI builds

To review:
- Download some artifacts, and make sure you get what you would expect: https://github.com/coin-or/CoinUtils/actions/runs/793951395

### CODE REVIEW

**Comment by xmunoz** [comment]
For reasons that I can't even begin to speculate about, some of the builds fail when ASAN is turned on :disappointed:

**Comment by xmunoz** [comment]
So apparently Ubuntu 18.04 and 20.04 have the exact same kernel version. This is a problem because I'm putting the kernel version in the file name, which causes the packages from these two OS versions to overwrite each other. Take a look at the artifacts for the latest build @tkralphs: https://github.com/coin-or/CoinUtils/actions/runs/794137737

Notice how there are only 7 artifacts, but 9 builds. How should we move forward?

**Comment by tkralphs** [comment]
I guess the naming should indicate binary compatibility, but I have to admit that my understanding of binary compatibility is murky. There seems to be no definitive source that really talks about it authoritatively. There's lots of stuff on StackOverflow, but it's hard to tell what is correct. Julia seems to do this extremely well and if you look here, you can see how many different platforms they build for: 

https://github.com/JuliaBinaryWrappers/Cbc_jll.jl/releases/tag/Cbc-v200.1000.500%2B0. 

At some point, we could end up just pointing people to these binaries, but they currently don't work if you just drop them in, they only work inside Julia. But anyway, you can see how they build their name strings up here: 

https://github.com/JuliaBinaryWrappers/Cbc_jll.jl#platforms

I just did a little Googling and found this, though, which seems to be a good enough standard to go off of for now:

https://hepsoftwarefoundation.org/notes/HSF-TN-2018-01.pdf

It's pretty close to what I was already trying to do and is at least documented so that the names can be understood by a little reading. What do you think of that?

**Comment by svigerske** [comment]
> So apparently Ubuntu 18.04 and 20.04 have the exact same kernel version. This is a problem because I'm putting the kernel version in the file name, which causes the packages from these two OS versions to overwrite each other. Take a look at the artifacts for the latest build @tkralphs: https://github.com/coin-or/CoinUtils/actions/runs/794137737
> 
> Notice how there are only 7 artifacts, but 9 builds. How should we move forward?

Why would one put the kernel version in the the artifact name?
What matters are the CPU architecture (arm, intel, 32bit, 64bit), the OS itself (Linux, macOS, WinNT, DOS, ...) and minimal versions of dependencies (e.g., C runtime (glibc), C++ runtime (libstdc++), Fortran runtime (libgfortran), if used and not linked in). The Linux kernel version isn't really relevant.

**Comment by xmunoz** [comment]
All good information! Thank  you, I'll update the PR shortly.

**Comment by xmunoz** [comment]
> What matters are the CPU architecture

Is this the output of `uname -p`? Some other command?

**Comment by svigerske** [comment]
> > What matters are the CPU architecture
> 
> Is this the output of `uname -p`? Some other command?

On my system, it says unknown for `uname -p` (and the man page says non-portable).

`uname -m` seems to work on the mac, linux, and windows systems I tried and gives a x86_64.

**Comment by xmunoz** [comment]
Cool, that's what the PR is doing currently.

How do you guys feel about just using the script referenced by that paper that Ted linked above to compute the archive name. It's this: https://github.com/HSF/tools/blob/master/hsf_get_platform.py

Of course we would prepend the string this generates with the project name and tag. This script would largely replace the "Compute environment variables" step.

**Comment by tkralphs** [comment]
At a glance, this looks to be a good way to compute the archive name and much better than my hacky script. We can always fork it and modify it, but for now, I would say just use it and see what the results look like.

**Comment by svigerske** [comment]
> Cool, that's what the PR is doing currently.
> 
> How do you guys feel about just using the script referenced by that paper that Ted linked above to compute the archive name. It's this: https://github.com/HSF/tools/blob/master/hsf_get_platform.py

Not for me to decide (and I deviated too much from my don't-waste-time-on-binary-distributions attitude here already :)), but the script seems to figure out what was used to build libraries (OS version, compiler version). However, I would find it more useful to say what is required to use the libraries, i.e.,
- glibc version (https://benohead.com/blog/2015/01/28/linux-check-glibc-version/ or look at `ldd -v` output)
- libstdc++ C++ API version (look at `ldd -v` output)
- libgfortran version (look at `ldd -v` output)
- macOS version requirement (`MACOSX_DEPLOYMENT_TARGET` env variable)
- MSVS runtime libraries version

**Comment by xmunoz** [comment]
@svigerske This is the output on my laptop:
```
$ ldd -v glpsol 
	linux-vdso.so.1 (0x00007ffe7fc79000)
	libcoinglpk.so.40 => /home/user/workspace/dist/lib/libcoinglpk.so.40 (0x00007f28a52d2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f28a5168000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f28a4f7e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f28a53de000)

	Version information:
	./glpsol:
		libm.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libm.so.6
		libc.so.6 (GLIBC_2.3) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
	/home/user/workspace/dist/lib/libcoinglpk.so.40:
		libm.so.6 (GLIBC_2.29) => /lib/x86_64-linux-gnu/libm.so.6
		libm.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libm.so.6
		libc.so.6 (GLIBC_2.11) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.3) => /lib/x86_64-linux-gnu/libc.so.6
	/lib/x86_64-linux-gnu/libm.so.6:
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
	/lib/x86_64-linux-gnu/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
```

This is a lot to parse! I'm going to propose that we do the cheap, easy thing for now, with the acknowledgement that it's suboptimal. For the future, I've created a separate issue so that we can loop back around to improving the naming convention when there is more energy to do so: #162

**Comment by svigerske** [comment]
> @svigerske This is the output on my laptop:

Hmm, is this from literally typing `ldd -v` + Enter?
Try with a library name as well.
```
$ ldd -v src/Interfaces/.libs/libipopt.so
	linux-vdso.so.1 (0x00007ffe4c19d000)
	libcoinhsl.so.2 => /my/path/to/install/lib/libcoinhsl.so.2 (0x00007f3818915000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f3818245000)
	libopenblas.so.3 => /usr/lib/libopenblas.so.3 (0x00007f3816f33000)
	libcoinmumps.so.0 => /my/path/to/install/lib/libcoinmumps.so.0 (0x00007f3816b5c000)
	libquadmath.so.0 => /usr/lib/libquadmath.so.0 (0x00007f3816b11000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f3816aee000)
	libgfortran.so.5 => /usr/lib/libgfortran.so.5 (0x00007f3816825000)
	libhwloc.so.15 => /usr/lib/libhwloc.so.15 (0x00007f38167cc000)
	libmetis.so => /usr/lib/libmetis.so (0x00007f3816764000)
	libmkl_intel_lp64.so => /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so (0x00007f3815a44000)
	libmkl_gnu_thread.so => /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so (0x00007f3813ce4000)
	libmkl_core.so => /opt/intel/mkl/lib/intel64/libmkl_core.so (0x00007f380f6a1000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f380f69a000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f380f4bd000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f380f378000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f380f1ab000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f381979e000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f380f191000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x00007f380f14e000)
	libudev.so.1 => /usr/lib/libudev.so.1 (0x00007f380f124000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f380f119000)

	Version information:
	src/Interfaces/.libs/libipopt.so:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libgfortran.so.5 (GFORTRAN_10) => /usr/lib/libgfortran.so.5
		libgfortran.so.5 (GFORTRAN_8) => /usr/lib/libgfortran.so.5
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.29) => /usr/lib/libm.so.6
		libdl.so.2 (GLIBC_2.2.5) => /usr/lib/libdl.so.2
		libstdc++.so.6 (CXXABI_1.3.8) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.15) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.9) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /usr/lib/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.21) => /usr/lib/libstdc++.so.6
		libc.so.6 (GLIBC_2.6) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.7) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libpthread.so.0 (GLIBC_2.3.2) => /usr/lib/libpthread.so.0
		libpthread.so.0 (GLIBC_2.2.5) => /usr/lib/libpthread.so.0
	/my/path/to/install/lib/libcoinhsl.so.2:
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libgomp.so.1 (GOMP_4.0) => /usr/lib/libgomp.so.1
		libgomp.so.1 (OMP_3.0) => /usr/lib/libgomp.so.1
		libgomp.so.1 (GOMP_2.0) => /usr/lib/libgomp.so.1
		libgomp.so.1 (OMP_1.0) => /usr/lib/libgomp.so.1
		libgomp.so.1 (GOMP_1.0) => /usr/lib/libgomp.so.1
		libm.so.6 (GLIBC_2.27) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.29) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
		libgfortran.so.5 (GFORTRAN_10) => /usr/lib/libgfortran.so.5
		libgfortran.so.5 (GFORTRAN_8) => /usr/lib/libgfortran.so.5
	/usr/lib/liblapack.so.3:
		libgcc_s.so.1 (GCC_4.0.0) => /usr/lib/libgcc_s.so.1
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libgfortran.so.5 (GFORTRAN_8) => /usr/lib/libgfortran.so.5
		libm.so.6 (GLIBC_2.29) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.27) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
	/usr/lib/libopenblas.so.3:
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
		libpthread.so.0 (GLIBC_2.2.5) => /usr/lib/libpthread.so.0
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		libgomp.so.1 (GOMP_4.0) => /usr/lib/libgomp.so.1
		libgomp.so.1 (OMP_1.0) => /usr/lib/libgomp.so.1
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.7) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.6) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/my/path/to/install/lib/libcoinmumps.so.0:
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.29) => /usr/lib/libm.so.6
		libpthread.so.0 (GLIBC_2.3.2) => /usr/lib/libpthread.so.0
		libpthread.so.0 (GLIBC_2.2.5) => /usr/lib/libpthread.so.0
		libgfortran.so.5 (GFORTRAN_10) => /usr/lib/libgfortran.so.5
		libgfortran.so.5 (GFORTRAN_8) => /usr/lib/libgfortran.so.5
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libquadmath.so.0:
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.10) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libm.so.6 (GLIBC_2.23) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
	/usr/lib/libpthread.so.0:
		ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /usr/lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /usr/lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.32) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /usr/lib/libc.so.6
	/usr/lib/libgfortran.so.5:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		libm.so.6 (GLIBC_2.29) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.27) => /usr/lib/libm.so.6
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
		libgcc_s.so.1 (GCC_4.2.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_4.3.0) => /usr/lib/libgcc_s.so.1
		libquadmath.so.0 (QUADMATH_1.0) => /usr/lib/libquadmath.so.0
		libc.so.6 (GLIBC_2.15) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.6) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.33) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.7) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.25) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.17) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
	/usr/lib/libhwloc.so.15:
		libdl.so.2 (GLIBC_2.2.5) => /usr/lib/libdl.so.2
		libudev.so.1 (LIBUDEV_183) => /usr/lib/libudev.so.1
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
		libc.so.6 (GLIBC_2.32) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.6) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.8) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.7) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libmetis.so:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_2.11) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.7) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
	/opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so:
		libdl.so.2 (GLIBC_2.2.5) => /usr/lib/libdl.so.2
	/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so:
		libdl.so.2 (GLIBC_2.2.5) => /usr/lib/libdl.so.2
		libpthread.so.0 (GLIBC_2.2.5) => /usr/lib/libpthread.so.0
	/opt/intel/mkl/lib/intel64/libmkl_core.so:
		libdl.so.2 (GLIBC_2.2.5) => /usr/lib/libdl.so.2
		libpthread.so.0 (GLIBC_2.2.5) => /usr/lib/libpthread.so.0
	/usr/lib/libdl.so.2:
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /usr/lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_PRIVATE) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libstdc++.so.6:
		libm.so.6 (GLIBC_2.2.5) => /usr/lib/libm.so.6
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		libgcc_s.so.1 (GCC_4.2.0) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.4) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3) => /usr/lib/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.0) => /usr/lib/libgcc_s.so.1
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.6) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.33) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.18) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.16) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.17) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libm.so.6:
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /usr/lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /usr/lib/libc.so.6
	/usr/lib/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /usr/lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /usr/lib64/ld-linux-x86-64.so.2
	/usr/lib/libgcc_s.so.1:
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libgomp.so.1:
		libdl.so.2 (GLIBC_2.2.5) => /usr/lib/libdl.so.2
		libpthread.so.0 (GLIBC_2.3.4) => /usr/lib/libpthread.so.0
		libpthread.so.0 (GLIBC_2.2.5) => /usr/lib/libpthread.so.0
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.16) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.6) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.17) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.32) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/libudev.so.1:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /usr/lib64/ld-linux-x86-64.so.2
		libpthread.so.0 (GLIBC_2.2.5) => /usr/lib/libpthread.so.0
		libc.so.6 (GLIBC_2.3) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.9) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.25) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.28) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.16) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.8) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.7) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.33) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.26) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.30) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.17) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
	/usr/lib/librt.so.1:
		libpthread.so.0 (GLIBC_2.3.2) => /usr/lib/libpthread.so.0
		libpthread.so.0 (GLIBC_PRIVATE) => /usr/lib/libpthread.so.0
		libpthread.so.0 (GLIBC_2.2.5) => /usr/lib/libpthread.so.0
		libc.so.6 (GLIBC_2.32) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.14) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.4) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /usr/lib/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /usr/lib/libc.so.6
```

**Comment by xmunoz** [comment]
Sorry, submitted the comment prematurely, see above now.

**Comment by tkralphs** [comment]
We may be able to improve on the output of `hsf_get_platform`, but it is a vast improvement on what we're currently doing, so to keep moving ahead, let's use it. I'll wait for merging this until we get that in place unless @xmunoz says otherwise. everything else seems to look good!

**Comment by xmunoz** [comment]
Cool. @tkralphs how do you feel about forking the repo to COIN-OR? This isn't a pre-requisite for this PR (I can just reference the SHA of HEAD on master), but we might want to hack on it moving forward.

**Comment by xmunoz** [comment]
Lol turns out that script is extremely specific to what is running at CERN and we basically have to fork it and hack on it a bit to get it working with these build environments :(

**Comment by tkralphs** [comment]
> Lol turns out that script is extremely specific to what is running at CERN and we basically have to fork it and hack on it a bit to get it working with these build environments :(

Interesting, I did try it out first and it worked perfectly for me. I don't mind forking it, but we can put it in the coin-or-tools organization, which is for stuff like that. Or we could just blatantly copy it into coinbrew. What do you think?

**Comment by tkralphs** [comment]
Something weird is going on. It's getting a syntax error on a line it shouldn't even be reaching.
```
raise f"System {system} not supported"
```
On my system, if I force it to go to that line, it gives me a `TypeError`, but anyway, it shouldn't reach that line unless the `platform.system()` returns something unexpected.

**Comment by tkralphs** [comment]
I don't see anything specific to CERN, other than the fact that CERN might appear in the name of the Linux distro (I guess they have their own), but looks like it should work generically.

**Comment by xmunoz** [comment]
> > Lol turns out that script is extremely specific to what is running at CERN and we basically have to fork it and hack on it a bit to get it working with these build environments :(
> 
> Interesting, I did try it out first and it worked perfectly for me. I don't mind forking it, but we can put it in the coin-or-tools organization, which is for stuff like that. Or we could just blatantly copy it into coinbrew. What do you think?

I would prefer to fork it as is to COIN-OR, so that I can push fixes and send a PR to the upstream. There are two issues: there is a syntax error there, all exceptions need to be wrapped in the `Exception` base class, and second that the platform on the Github-hosted runners apparently isn't `Linux`.

I could also fork this to my account and push the required fixes, which could help us get this PR merged, but I think that's less sustainable long-term.

**Comment by xmunoz** [comment]
> I don't see anything specific to CERN, other than the fact that CERN might appear in the name of the Linux distro (I guess they have their own), but looks like it should work generically.

This script is obviously tailored to their needs, which is why it doesn't work out of the box for us. One example: formatting strings were introduced in Python3.6. They use formatting strings in their script, presumably because they only intend to run this script on machines with >= Python 3.6, but on our Ubuntu 16.04 build machine, only Python3.5 is supported, causing a Syntax error. I have modified the script for compatibility with all the Python3 versions installed on our build boxes, but this is one such example of what I meant.

**Comment by xmunoz** [comment]
The script has a problem recognizing the gcc compiler on MacOS...

**Comment by tkralphs** [comment]
I see, OK, I was wondering if the errors were due to Python versions. But it at least looks like cleanup won't be too bad and it's a good starting point. Maybe since we're fixing p the script anyway, could we just get rid of the `-all` unless there is a string specified with the `-b` flag to the script?

**Comment by xmunoz** [comment]
I'm fine with that, but I'd like this forked repo to live in this organization before we merge. I don't want my Github account to be a critical dependency for the COIN-OR build system.

**Comment by tkralphs** [comment]
You can transfer ownership to coin-or-tools anytime and I'll accept the transfer.

**Comment by tkralphs** [comment]
Looks nice now!

**Comment by xmunoz** [comment]
> You can transfer ownership to coin-or-tools anytime and I'll accept the transfer.

Captura de pantalla de 2021-04-30 09-03-56

I apparently can't. In the area where the transfer button lives, there is this caveat:

>  Transfer this repository to another user or to an organization where you have the ability to create repositories.

So, a couple of options:

- You fork [this repo](https://github.com/HSF/tools/) to coin-or-tools and give me write access. I will add my commits to that fork, OR
- You grant me the ability to create repositories in coin-or-tools and I transfer ownership of my fork

Whichever one we go with, I think we should to change the repo name to something that reflects our use of this code, maybe `package-name-generator`?

**Comment by tkralphs** [comment]
Hmm, that is weird. I've had people transfer projects to COIN-OR multiple times in the past, but maybe it is just easier for me to fork the repo and then we can replicate what you did. And yes, I agree, I was also thinking of changing the name of the repo.

**Comment by tkralphs** [comment]
OK, I created a fork here: https://github.com/coin-or-tools/platform-analysis-tools and gave @xmunoz access to it.

**Review by tkralphs — APPROVED** [review]
Looks good, thanks!

**Comment by tkralphs** [comment]
I was about to do the merge, but noticed the changes to `Makefile.in`. Unfortunately, `Makefile.in` is auto-generated, so that is a fix that needs to ultimately be made in [BuildTools](https://github.com/coin-or-tools/BuildTools). I have to trace the reasons why it is still referencing `README` instead of `README.md`. We did recently overhaul the build system and part of that was some modernization, including doing replacements like that. So that is a much bigger-picture thing that is something repeated across many projects that all use the same build system. I guess it probably doesn't hurt much to merge the change, but that is also something that will eventually be over-written if we don't fix the root cause.

**Comment by tkralphs** [comment]
The source of the line you changed is here: 
https://github.com/coin-or-tools/BuildTools/blob/ea783d8479edc393559f89587fc86e26beed6d83/Makemain.inc#L38
We should think about whether README is needed here or not. I think the main purposes is that some projects may still have a `README` and not a `README.md`. It might be worth opening an issue on this.

**Pull request merged**
