### PR TITLE
Add the Contributor Covenent as the code of conduct

### LINKED ISSUE #172: Adopt a code of conduct
I have scoured the documentation and haven't found an explicitly-articulated code of conduct. This would be a good thing to do in general, and specifically would help us grow the COIN-OR community and apply for funding.

I recommend the [Contributor Covenant](https://www.contributor-covenant.org/).

The exit criteria for this issue: Adopt a code of conduct for this repository and this organization, and identify an email address where users can report violations.

### PR DESCRIPTION
**Pull request by xmunoz**
~~- Follow up task: create a private mailing list for COC violations reporting,
  and add users to that list (conduct@list.coin-or.org)~~
^ This is already done. The mailing list is code-of-conduct@coin-or.org.

Fixes #172.

I'm adding all of core contributors to this repository for approval to confirm that everyone agrees with this PR. Please add anyone that I might have missed! 

If we can get consensus, then I'll roll out this change to other repositories in the coin-or organization.

### CODE REVIEW

**Comment by svigerske** [comment]
>     * Follow up task: create a private mailing list for COC violations reporting,
>       and add users to that list ([conduct@list.coin-or.org](mailto:conduct@list.coin-or.org))
> 
> 
> Fixes #172.
> 
> I'm adding all of core contributors to this repository for approval to confirm that everyone agrees with this PR. Please add anyone that I might have missed!
> 
> If we can get consensus, then I'll roll out this change to other repositories in the coin-or organization.

It should be up to the project managers of the repositories whether they want to add such a thing.   
Further, a CoinUtils PR is not a good place to reach out to everyone. There is a project managers mailing list.

**Review by svigerske — APPROVED** [review]

**Comment by xmunoz** [comment]
> There is a project managers mailing list.

Excellent! I will also send a message there. Could you share the mailing list alias? I know there is this [list of mailing lists](https://list.coin-or.org/mailman/listinfo/) but it's not clear to me which is the right one to reach out to.

**Comment by svigerske** [comment]
https://list.coin-or.org/mailman/listinfo/project-managers

**Comment by xmunoz** [comment]
@tkralphs will bring this up to the board directly and the circle back with the results of that discussion. The project managers list might be deprecated and/or moving to google groups apparently.

**Comment by svigerske** [comment]
For years now, the mailing lists are moving to google groups. Recently, they are also moving to GitHub discussions.
But still, the mailing lists exist and are open for posts. To contact with all project managers, the project managers list is also the only option I know of.

**Comment by xmunoz** [comment]
@tkralphs how do you feel about this change? If you approve, I'll go ahead and send a PR to coinbrew so that the README generation automatically adds the link to the CoC like this.

**Comment by xmunoz** [comment]
Another ping! I'd like to get one more approval before merging, though that isn't technically necessary.

**Comment by tkralphs** [comment]
Sorry for taking such a long time to review this simple change. This is totally fine with me, although for all the projects in the Optimization Suite, we actually need to change only the auto-generation script.

**Review by tkralphs — APPROVED** [review]

**Pull request merged**
