### PR TITLE
Enable fast_finish for AppVeyor builds

### LINKED ISSUE #158: Appveyor CI is painfully slow
I've open a few PRs to this repository now and I've noticed that it often takes hours for the AppVeyor builds to complete. Upon further investigation, I've identified the following inefficiencies:

- Builds are sequential, with each platform taking 6-10 minutes to complete
- There are a large number of builds (10), including for platforms that are now 6 years old and deprecated by Microsoft
  - This means that every commit takes over an hour for a full build to complete
- Fast fail is not configured, so builds will continue even if one fails
-  "Rolling builds" option is not enabled, meaning that the queue fills up with old commits, and will build for every single one, even if there are newer commits.

Most of these options are configurable in the `appveyor.yml` file, but I believe the last on is only changeable through the UI. @tkralphs can you grant me access to the COIN-OR project on appveyor? I'd like to see what other configuration options are available. For the rest of these issues, I'll send a PR.

### PR DESCRIPTION
**Pull request by xmunoz**
Eliminate builds for VisualStudio 2015.

Fixes #158.

### CODE REVIEW

**Comment by xmunoz** [comment]
I manually cancelled the "continuous-integration/appveyor/pr" build, hoping that it would speed up the queue time for the branch build. Guess Appveyor is just slow.

**Comment by tkralphs** [comment]
Yes, Appveyor is glacially slow :).

**Review by tkralphs — COMMENTED** [review]
So your thinking is to eliminate the automated creation of appveyor.yml? Or to change how it's done? Getting rid of appveyor.pre will break that. Actually, if we're basically just leaving appveyor as is, I can re-generate appveyor.yml for the whole stack to eliminate VS 2015 rather than hand editing. Otherwise, we'll be editing 20 appveyor.yml files in the end and I do want to keep them all more or less identical in terms of the matrix, flags, etc. Scripting is the easiest way to ensure that.

**Comment by xmunoz** [comment]
JK about removing that. I think it's fine to keep it.

**Comment by xmunoz** [comment]
Sweet, looks like that config option worked!

**Review by tkralphs — APPROVED** [review]
Looks good!

**Pull request merged**
